/* Generated By:JavaCC: Do not edit this line. CCALVisitor.java Version 5.0 */
public interface CCALVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Prog node, Object data);
  public Object visit(VarDecl node, Object data);
  public Object visit(ConstDecl node, Object data);
  public Object visit(ConstAssign node, Object data);
  public Object visit(Func node, Object data);
  public Object visit(FuncRet node, Object data);
  public Object visit(Type node, Object data);
  public Object visit(ParamList node, Object data);
  public Object visit(Main node, Object data);
  public Object visit(Stm node, Object data);
  public Object visit(Assign node, Object data);
  public Object visit(PlusOp node, Object data);
  public Object visit(MinOp node, Object data);
  public Object visit(Num node, Object data);
  public Object visit(Bool node, Object data);
  public Object visit(OrOp node, Object data);
  public Object visit(AndOp node, Object data);
  public Object visit(EqOp node, Object data);
  public Object visit(NotOp node, Object data);
  public Object visit(LtOp node, Object data);
  public Object visit(LtEqOp node, Object data);
  public Object visit(GtOp node, Object data);
  public Object visit(GtEqOp node, Object data);
  public Object visit(ArgList node, Object data);
  public Object visit(identifier node, Object data);
}
/* JavaCC - OriginalChecksum=61c3e6b14de32b2215d55d7a7be360e4 (do not edit this line) */
